#!/bin/bash

# General settings
yabai -m config layout bsp
yabai -m config window_gap 8
yabai -m config top_padding 10
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10

# Smart window behavior
yabai -m config window_shadow off
yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse off

# Auto-floating specific apps
yabai -m rule --add app="System Preferences" manage=off
yabai -m rule --add app="System Settings" manage=off
yabai -m rule --add app="Finder" manage=off
yabai -m rule --add title="Preferences" manage=off
